# Generated by Django 4.0.4 on 2022-05-08 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movieshow_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshow',
            name='director',
            field=models.CharField(default='Unknow Director', max_length=50),
        ),
        migrations.AddField(
            model_name='movieshow',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieshow',
            name='target_audience',
            field=models.CharField(choices=[('G', 'G rated'), ('PG', 'PG rated'), ('PG-13', 'PG-13 rated'), ('R', 'R rated'), ('NC-17', 'NC-17 rated')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
