# Generated by Django 4.0.4 on 2022-05-21 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_target_audience_movieshow_age_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='director',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='movieshow',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movieshow',
            name='runtime',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
